In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi /180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [12]:
numero_random = np.random.randint(
    11 # el arreglo ira dle 0 al 11 [0,11[
)
numero_random

9

In [36]:
numero_random_neg = np.random.randint(-9,2)
numero_random_neg

-5

In [37]:
arreglo_random = np.random.randint(10, 20,8)
arreglo_random

array([16, 13, 10, 15, 17, 18, 14, 12])

In [38]:
np.random.rand(9)

array([0.90592774, 0.22306228, 0.6511506 , 0.06048992, 0.1803999 ,
       0.18049249, 0.98902145, 0.16531925, 0.61984574])

In [40]:
np.average(arreglo_random)

14.375

In [41]:
np.mean(arreglo_random)

14.375

In [42]:
np.median(arreglo_random)

14.5

In [44]:
np.std(arreglo_random)

2.496873044429772

In [45]:
np.var(arreglo_random)

6.234375

In [46]:
arreglo_random.mean()

14.375